export const ROLES = { STUDENT: 'STUDENT', INSTRUCTOR: 'INSTRUCTOR', ADMIN: 'ADMIN' };
export const LESSON_TYPES = { VIDEO: 'VIDEO', PDF: 'PDF', TEXT: 'TEXT', QUIZ: 'QUIZ' };
export const QUIZ_TYPES = { MCQ: 'MCQ', FILL_BLANK: 'FILL_BLANK', CODING: 'CODING' };
export const COURSE_LEVELS = { BEGINNER: 'BEGINNER', INTERMEDIATE: 'INTERMEDIATE', ADVANCED: 'ADVANCED' };
export const PAYMENT_STATUS = { PENDING: 'PENDING', SUCCESS: 'SUCCESS', FAILED: 'FAILED', REFUNDED: 'REFUNDED' };
export const NOTIFICATION_TYPES = { INFO: 'INFO', SUCCESS: 'SUCCESS', WARNING: 'WARNING', ERROR: 'ERROR' };
